include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Enable additional rules
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - join_return_with_assignment
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_elements_to_conditional_expressions
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - recursive_getters
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_with_setters
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_full_hex_values_for_colors
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - use_setters_instead_of_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - prefer_relative_imports

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 100
    number-of-parameters: 4
    maximum-nesting-level: 5
  rules:
    - newline-before-return
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - no-object-declaration
    - avoid-redundant-type-annotations
    - avoid-unnecessary-type-casts
    - avoid-unnecessary-type-arguments
    - avoid-wrapping-in-padding
    - avoid-wrapping-in-expanded
    - avoid-wrapping-in-sized-box
    - avoid-wrapping-in-column-row
    - avoid-wrapping-in-stack
    - avoid-wrapping-in-center
    - avoid-wrapping-in-align
    - avoid-wrapping-in-constrained-box
    - avoid-wrapping-in-flexible
    - avoid-wrapping-in-single-child-scroll-view
    - avoid-wrapping-in-list-view
    - avoid-wrapping-in-gesture-detector
    - avoid-wrapping-in-inkwell
    - avoid-wrapping-in-material
    - avoid-wrapping-in-card
    - avoid-wrapping-in-container
    - avoid-wrapping-in-decorated-box
    - avoid-wrapping-in-fractionally-sized-box
    - avoid-wrapping-in-fitted-box
    - avoid-wrapping-in-overflow-box
    - avoid-wrapping-in-positioned
    - avoid-wrapping-in-safe-area
    - avoid-wrapping-in-sliver-fill-remaining
    - avoid-wrapping-in-sliver-to-box-adapter
    - avoid-wrapping-in-transform
    - avoid-wrapping-in-offstage
    - avoid-wrapping-in-opacity
    - avoid-wrapping-in-absorb-pointer
    - avoid-wrapping-in-ignore-pointer
    - avoid-wrapping-in-hero
    - avoid-wrapping-in-clip-r-rect
    - avoid-wrapping-in-clip-oval
    - avoid-wrapping-in-clip-path
    - avoid-wrapping-in-custom-paint
    - avoid-wrapping-in-custom-scroll-view
    - avoid-wrapping-in-nested-scroll-view
    - avoid-wrapping-in-page-view
    - avoid-wrapping-in-tab-bar-view
    - avoid-wrapping-in-indexed-stack
    - avoid-wrapping-in-animated-switcher
    - avoid-wrapping-in-fade-transition
    - avoid-wrapping-in-scale-transition
    - avoid-wrapping-in-slide-transition
    - avoid-wrapping-in-rotation-transition
    - avoid-wrapping-in-size-transition
    - avoid-wrapping-in-decorated-box-transition
    - avoid-wrapping-in-position-transition
    - avoid-wrapping-in-relative-positioned-transition
    - avoid-wrapping-in-align-transition
    - avoid-wrapping-in-default-text-style
    - avoid-wrapping-in-hero-controller
    - avoid-wrapping-in-inherited-widget
    - avoid-wrapping-in-media-query
    - avoid-wrapping-in-navigator
    - avoid-wrapping-in-overlay
    - avoid-wrapping-in-semantics
    - avoid-wrapping-in-shader-mask
    - avoid-wrapping-in-absorb-pointer
    - avoid-wrapping-in-ignore-pointer
    - avoid-wrapping-in-offstage
    - avoid-wrapping-in-opacity
    - avoid-wrapping-in-transform
    - avoid-wrapping-in-clip-r-rect
    - avoid-wrapping-in-clip-oval
    - avoid-wrapping-in-clip-path
    - avoid-wrapping-in-custom-paint
    - avoid-wrapping-in-custom-scroll-view
    - avoid-wrapping-in-nested-scroll-view
    - avoid-wrapping-in-page-view
    - avoid-wrapping-in-tab-bar-view
    - avoid-wrapping-in-indexed-stack
    - avoid-wrapping-in-animated-switcher
    - avoid-wrapping-in-fade-transition
    - avoid-wrapping-in-scale-transition
    - avoid-wrapping-in-slide-transition
    - avoid-wrapping-in-rotation-transition
    - avoid-wrapping-in-size-transition
    - avoid-wrapping-in-decorated-box-transition
    - avoid-wrapping-in-position-transition
    - avoid-wrapping-in-relative-positioned-transition
    - avoid-wrapping-in-align-transition
    - avoid-wrapping-in-default-text-style
    - avoid-wrapping-in-hero-controller
    - avoid-wrapping-in-inherited-widget
    - avoid-wrapping-in-media-query
    - avoid-wrapping-in-navigator
    - avoid-wrapping-in-overlay
    - avoid-wrapping-in-semantics
    - avoid-wrapping-in-shader-mask
    - avoid-wrapping-in-absorb-pointer
    - avoid-wrapping-in-ignore-pointer
    - avoid-wrapping-in-offstage
    - avoid-wrapping-in-opacity
    - avoid-wrapping-in-transform
    - avoid-wrapping-in-clip-r-rect
    - avoid-wrapping-in-clip-oval
    - avoid-wrapping-in-clip-path
    - avoid-wrapping-in-custom-paint
    - avoid-wrapping-in-custom-scroll-view
    - avoid-wrapping-in-nested-scroll-view
    - avoid-wrapping-in-page-view
    - avoid-wrapping-in-tab-bar-view
    - avoid-wrapping-in-indexed-stack
    - avoid-wrapping-in-animated-switcher
    - avoid-wrapping-in-fade-transition
    - avoid-wrapping-in-scale-transition
    - avoid-wrapping-in-slide-transition
    - avoid-wrapping-in-rotation-transition
    - avoid-wrapping-in-size-transition
    - avoid-wrapping-in-decorated-box-transition
    - avoid-wrapping-in-position-transition
    - avoid-wrapping-in-relative-positioned-transition
    - avoid-wrapping-in-align-transition
    - avoid-wrapping-in-default-text-style
    - avoid-wrapping-in-hero-controller
    - avoid-wrapping-in-inherited-widget
    - avoid-wrapping-in-media-query
    - avoid-wrapping-in-navigator
    - avoid-wrapping-in-overlay
    - avoid-wrapping-in-semantics
    - avoid-wrapping-in-shader-mask
