name: skyscraper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: 3.0.0-dev.17
  freezed_annotation: 3.1.0
  go_router: 14.1.1
  json_annotation: 4.9.0
  riverpod_annotation: 3.0.0-dev.17

dev_dependencies:
  build_runner: 2.6.0
  custom_lint: 0.8.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.0
  json_serializable: 6.10.0
  mockito: ^5.4.5
  riverpod_generator: 3.0.0-dev.17
  riverpod_lint: 3.0.0-dev.17
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/